<?php


use PGMB\Premium\Taxonomies\TaxonomyField;

if ( class_exists( '\PGMB\Premium\Taxonomies\TaxonomyField' ) ) {
	class PGMB_LocationTaxonomyField extends TaxonomyField {

		protected $field_types = [
			'singlecheck',
			'business_selector'
		];

		public static function init( $taxonomy, $field_id, $field_type, $field_label, $field_description, $field_options = [] ) {
			$instance = parent::init( $taxonomy, $field_id, $field_type, $field_label, $field_description, $field_options ); // TODO: Change the autogenerated stub

			add_action("{$taxonomy}_add_form_fields", [$instance, 'draw_add_field'], 10, 2);
			add_action("{$taxonomy}_edit_form_fields", [$instance, 'draw_edit_field'], 10, 2);
			add_action("edited_{$taxonomy}", [$instance, 'save_field'], 10, 2);
			add_action("created_{$taxonomy}", [$instance, 'save_field'], 10, 2);
			return $instance;
		}

		protected function draw_input( $value = null ) {
			if ( ! class_exists( '\PGMB\Premium\Components\MultiAccountBusinessSelector' ) ) {
				return;
			}
			global $post_to_google_my_business;
			$container = $post_to_google_my_business->get_container();
			$selector = new \PGMB\Premium\Components\MultiAccountBusinessSelector($container['google_my_business_api'], $container['user_manager'], $container['gmb_cookie_api']);
			$selector->set_field_name( $this->field_id );

			if ( function_exists( 'mbp_fs' ) && mbp_fs()->is_plan_or_trial( 'business' ) ) {
				$selector->enable_multiple( true );
			}

			if ( $value ) {
				$value = is_array($value)? $value : [$value];
				//Upgrade if old format
				if(isset($value[0]) && !is_array($value[0])){
					preg_match('/\d+/', $value[0], $matches);

					if(!isset($matches[0])){ return ; }

					$user_id = $matches[0];
					$value = [$user_id => $value];
				}
				$selector->set_selected_locations( $value );
			}


			echo $selector->generate();
		}

		public function save_field( $term_id, $tt_id ) {
			if ( ! isset( $_POST["{$this->field_id}_submitted"] ) ) {
				return;
			}
			if ( ! isset( $_POST[ $this->field_id ] ) || $this->field_type !== 'business_selector' ) {
				return;
			}
//			error_log(print_r($_POST[ $this->field_id ], true));
//			if ( is_array( $_POST[ $this->field_id ] ) ) {
//				$value = array_map( function ( $row ) {
//					return sanitize_text_field( $row );
//				}, $_POST[ $this->field_id ] );
//			} else {
//				$value = sanitize_text_field( $_POST[ $this->field_id ] );
//			}

			update_term_meta( $term_id, $this->field_id, $_POST[ $this->field_id ] );
		}

	}
}


//use PGMB\Premium\Taxonomies\TaxonomyField;
//
//class LocationTaxonomyField extends TaxonomyField {
//
//	protected $field_types = [
//		'singlecheck',
//		'business_selector'
//	];
//
//	protected function draw_input($value = null){
//		global $post_to_google_my_business;
//		$container = $post_to_google_my_business->get_container();
//		$selector = new \PGMB\Components\BusinessSelector($container['google_my_business_api']);
//		$selector->set_field_name($this->field_id);
//		if($value){
//			$selector->set_selected_locations($value);
//		}
//
//		echo $selector->generate();
//	}
//
//
//}
